### ISSUE TITLE
Repeat name

### ISSUE THREAD

**Issue by thornbirdblue** [thornbirdblue/git-stat#1]
!!!WARN!!! Sheet Name: vendor_qcom_proprietary_mm-cam contain of - will delete!!!
Traceback (most recent call last):
  File "/opt4/liuchangjian/bin/git-stat.py", line 744, in <module>
    GoToDir(spath)
  File "/opt4/liuchangjian/bin/git-stat.py", line 539, in GoToDir
    GitRec.SaveRepo(workbook,file)
  File "/opt4/liuchangjian/bin/git-stat.py", line 333, in SaveRepo
    ws = wb.add_worksheet(SheetName)
  File "/usr/local/lib/python2.7/dist-packages/XlsxWriter-0.7.6-py2.7.egg/xlsxwriter/workbook.py", line 169, in add_worksheet
    return self._add_sheet(name, is_chartsheet=False)
  File "/usr/local/lib/python2.7/dist-packages/XlsxWriter-0.7.6-py2.7.egg/xlsxwriter/workbook.py", line 548, in _add_sheet
    name = self._check_sheetname(name, is_chartsheet)
  File "/usr/local/lib/python2.7/dist-packages/XlsxWriter-0.7.6-py2.7.egg/xlsxwriter/workbook.py", line 615, in _check_sheetname
    sheetname)
Exception: Sheetname 'vendor_qcom_proprietary_mmcam', with case ignored, is already in use.

**Comment by thornbirdblue** [comment]
commit 1d16734db63fd4c42ec580915abdc4eb0df3483c
